/** KEY ROOM — customer-facing design tokens (업계누적 기준선 UI 통일). */

export const LG = {
  bg: "#F7F8FC",
  text: "#172033",
  textMuted: "#6B7280",
  textSoft: "#6B7280",
  border: "#E7EAF0",
  borderStrong: "#E7EAF0",
  surface: "#FFFFFF",
  button: "#14244A",
  buttonHover: "#0F1A36",
  buttonDisabled: "#9CA3AF",
  userBubble: "#EEF3FF",
  assistantBubble: "#FFFFFF",
  chipBg: "#FFFFFF",
  chipBorder: "#E7EAF0",
  sidebarBg: "#FFFFFF",
  inputBg: "#FFFFFF",
  navy: "#14244A",
  accent: "#315EF6",
  accentSoft: "#EEF3FF",
  verified: "#167C6A",
  verifiedBg: "#EAF7F3",
  needs: "#C87516",
  needsBg: "#FFF4E5",
  needCheck: "#64748B",
  needCheckBg: "#F1F5F9",
  overlap: "#7656C8",
  overlapBg: "#F1EDFF",
  summaryBg: "#EEF3FF",
  /** Prefer border cards; keep shadow extremely light. */
  shadow: "none",
  shadowSoft: "0 1px 2px rgba(20, 36, 74, 0.04)",
  serif: 'var(--font-serif, "Playfair Display", Georgia, "Times New Roman", serif)',
  sans: '"Pretendard", "Apple SD Gothic Neo", "Malgun Gothic", "Segoe UI", system-ui, sans-serif',
};
