/** KEY ROOM — customer-facing design tokens (보험 전문 AI 상담실). */

export const LG = {
  bg: "#F9F8F6",
  text: "#1A2B4B",
  textMuted: "#5B6475",
  textSoft: "#8B93A7",
  border: "#E5E7EB",
  borderStrong: "#D1D5DB",
  surface: "#FFFFFF",
  button: "#1A2B4B",
  buttonHover: "#0F1C33",
  buttonDisabled: "#9CA3AF",
  userBubble: "#E8F2FF",
  assistantBubble: "#FFFFFF",
  chipBg: "#FFFFFF",
  chipBorder: "#E5E7EB",
  sidebarBg: "#FFFFFF",
  inputBg: "#FFFFFF",
  navy: "#1A2B4B",
  accent: "#3B82F6",
  verified: "#2563EB",
  needs: "#D97706",
  shadow: "0 1px 3px rgba(26, 43, 75, 0.06)",
  shadowSoft: "0 4px 20px rgba(26, 43, 75, 0.06)",
  serif: 'var(--font-serif, "Playfair Display", Georgia, "Times New Roman", serif)',
  sans: '"Pretendard", "Apple SD Gothic Neo", "Malgun Gothic", "Segoe UI", system-ui, sans-serif',
};
